### ISSUE TITLE
Several versions in one file

### ISSUE THREAD

**Issue by GingerTe** [Greewil/version-update-helper#15]
**Is your feature request related to a problem? Please describe.**
Some version files (f.e. pyproject.toml) have several versions in one file, and vuh can't process that

**Describe the solution you'd like**
In version regexp match if there are more than one coincidence auto take first of them

**Additional context**
If we should take second version from file, it's ok if we mark that with comment

**Comment by Greewil** [comment]
Solved in 2.5.0 (https://github.com/Greewil/version-update-helper/releases/tag/v2.5.0)
